### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by Carreau**
@gnestor can you: 

- close: yes/no
- label: yes/no
- merge: yes/no

etc...

### CODE REVIEW

**Comment by mpacer** [comment]
Close: yes
label: yes
merge: yes

**Comment by mpacer** [comment]
Squash & merge: yes
rebase & merge: yes

**Comment by gnestor** [comment]
Close and merge: No
Label: Yes

**Comment by Carreau** [comment]
milestones ?

**Comment by gnestor** [comment]
No milestones

**Comment by gnestor** [comment]
A picture is worth a thousand words: 

Screen Shot 2019-06-26 at 5 26 55 PM

**Pull request closed without merging**
